# Generated by Django 2.0 on 2018-01-01 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('traceback', models.TextField()),
                ('time_recorded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
